services:

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: recommendation-api
    ports:
      - "8000:8000"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: recommendation-app
    ports:
      - "8501:8501"
    command: streamlit run app/app.py --server.address=0.0.0.0
    depends_on:
      - api
